parameters:
#    school_teacher.example.class: School\TeacherBundle\Example

services:
#    school_teacher.example:
#        class: %school_teacher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
