bulletin:
    path:     /
    defaults: { _controller: "SchoolNoteBundle:Bulletin:index" }
        
bulletin_seq_student:
    path:     /classe-{idClasse}/eleve-{idEleve}/sequence-{idSeq}/annee-{idAnnee}
    defaults: { _controller: "SchoolNoteBundle:Bulletin:bulletinStudent" }
    requirements:
        idEleve: \d+
        idSeq: \d+
        idClasse: \d+


student_performance:
    path:     /performances/eleve-{idEleve}
    defaults: { _controller: "SchoolNoteBundle:Bulletin:performances" }
    requirements:
        idEleve: \d+

bulletin_seq_classe:
    path:     /classe-{idClasse}/sequence-{idSeq}/annee-{idAnnee}
    defaults: { _controller: "SchoolNoteBundle:Bulletin:bulletinTestClasse" }
    requirements:
        idSeq: \d+
        idClasse: \d+