evaluation:
    path:     /
    defaults: { _controller: "SchoolNoteBundle:Evaluation:index" }

evaluation_show:
    path:     /{id}/show
    defaults: { _controller: "SchoolNoteBundle:Evaluation:show" }

evaluation_new:
    path:     /new
    defaults: { _controller: "SchoolNoteBundle:Evaluation:new" }

evaluation_create:
    path:     /create
    defaults: { _controller: "SchoolNoteBundle:Evaluation:create" }
    requirements: { _method: post }

evaluation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SchoolNoteBundle:Evaluation:edit" }

evaluation_update:
    path:     /{id}/update
    defaults: { _controller: "SchoolNoteBundle:Evaluation:update" }
    requirements: { _method: post|put }

evaluation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SchoolNoteBundle:Evaluation:delete" }
    requirements: { _method: post|delete }

note_add:
    path: /{id}/{idSeq}/{idMat}/notes/add
    defaults: { _controller: "SchoolNoteBundle:Evaluation:note"}
    #requirements: { _method: post|put }

note_editnote:
    path: /{id}/{idSeq}/{idMat}/notes/edit
    defaults: { _controller: "SchoolNoteBundle:Evaluation:editnote"}
    #requirements: { _method: post|put }