evaluation:
    path:     /
    defaults: { _controller: "SchoolNoteBundle:Evaluation:index" }

statistiques:
    path:     /{idSequence}/{idMatiere}/{idEnseignant}/statistiques
    defaults: { _controller: "SchoolNoteBundle:Evaluation:statistiques" }

bulletins:
    path:     /bulletins/{idSequence}/{idClasse}/{idStudent}
    defaults: { _controller: "SchoolNoteBundle:Evaluation:bulletins" }

evaluation_show:
    path:     /{id}/show
    defaults: { _controller: "SchoolNoteBundle:Evaluation:show" }

evaluation_new:
    path:     /new
    defaults: { _controller: "SchoolNoteBundle:Evaluation:new" }

evaluation_create:
    path:     /create
    defaults: { _controller: "SchoolNoteBundle:Evaluation:create" }
    requirements: { _method: post }

evaluation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SchoolNoteBundle:Evaluation:edit" }

evaluation_update:
    path:     /{id}/update
    defaults: { _controller: "SchoolNoteBundle:Evaluation:update" }
    requirements: { _method: post|put }

evaluation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SchoolNoteBundle:Evaluation:delete" }
    requirements: { _method: post|delete }

note_add:
    path: /classe-{id}/sequence-{idSeq}/matiere-{idMat}/annee-{idAnnee}/notes/add
    defaults: { _controller: "SchoolNoteBundle:Evaluation:note"}
    #requirements: { _method: post|put }

note_editnote:
    path: /classe-{id}/sequence-{idSeq}/matiere-{idMat}/annee-{idAnnee}/notes/edit
    defaults: { _controller: "SchoolNoteBundle:Evaluation:editnote"}
    requirements:
            id: \d+
            idSeq: \d+
            idMat: \d+
            idAnnee: \d+

note_inserer:
    path: /note-{idNote}/classe-{idClasse}/annee-{idAnnee}/notes/modifier
    defaults: { _controller: "SchoolNoteBundle:Evaluation:insererNote"}
    #requirements: { _method: post|put }