parameters:
#    rep_user.example.class: Rep\UserBundle\Example

services:
#    rep_user.example:
#        class: %rep_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
