<?php

namespace Proxies\__CG__\School\StudentBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Classe extends \School\StudentBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setAbreviation($abreviation)
    {
        $this->__load();
        return parent::setAbreviation($abreviation);
    }

    public function getAbreviation()
    {
        $this->__load();
        return parent::getAbreviation();
    }

    public function setClassePere(\School\StudentBundle\Entity\Classe $classePere = NULL)
    {
        $this->__load();
        return parent::setClassePere($classePere);
    }

    public function getClassePere()
    {
        $this->__load();
        return parent::getClassePere();
    }

    public function setCycle(\School\StudentBundle\Entity\Cycle $cycle = NULL)
    {
        $this->__load();
        return parent::setCycle($cycle);
    }

    public function getCycle()
    {
        $this->__load();
        return parent::getCycle();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'abreviation', 'classePere', 'cycle');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}