<?php

namespace Proxies\__CG__\School\StudentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscription extends \School\StudentBundle\Entity\Inscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'id', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'student', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'classe', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'avance', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'dateDerniereAvance', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'annee', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'status', 'listeEvaluations', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'nbreAbsence');
        }

        return array('__isInitialized__', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'id', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'student', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'classe', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'avance', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'dateDerniereAvance', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'annee', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'status', 'listeEvaluations', '' . "\0" . 'School\\StudentBundle\\Entity\\Inscription' . "\0" . 'nbreAbsence');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreAbsence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreAbsence', array());

        return parent::getNbreAbsence();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreAbsence($nbreAbsence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreAbsence', array($nbreAbsence));

        return parent::setNbreAbsence($nbreAbsence);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent(\School\StudentBundle\Entity\Student $student = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', array($student));

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', array());

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(\School\StudentBundle\Entity\Classe $classe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvance($avance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvance', array($avance));

        return parent::setAvance($avance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvance', array());

        return parent::getAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDerniereAvance($dateDerniereAvance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDerniereAvance', array($dateDerniereAvance));

        return parent::setDateDerniereAvance($dateDerniereAvance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDerniereAvance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDerniereAvance', array());

        return parent::getDateDerniereAvance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\School\ConfigBundle\Entity\Annee $annee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setListeEvaluations($listeEvaluations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListeEvaluations', array($listeEvaluations));

        return parent::setListeEvaluations($listeEvaluations);
    }

    /**
     * {@inheritDoc}
     */
    public function getListeEvaluations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeEvaluations', array());

        return parent::getListeEvaluations();
    }

}
