<?php

namespace Proxies\__CG__\School\StudentBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Student extends \School\StudentBundle\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setMatricule($matricule)
    {
        $this->__load();
        return parent::setMatricule($matricule);
    }

    public function getMatricule()
    {
        $this->__load();
        return parent::getMatricule();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setDateNaissance($dateNaissance)
    {
        $this->__load();
        return parent::setDateNaissance($dateNaissance);
    }

    public function getDateNaissance()
    {
        $this->__load();
        return parent::getDateNaissance();
    }

    public function setLieuNaissance($lieuNaissance)
    {
        $this->__load();
        return parent::setLieuNaissance($lieuNaissance);
    }

    public function getLieuNaissance()
    {
        $this->__load();
        return parent::getLieuNaissance();
    }

    public function setNomPere($nomPere)
    {
        $this->__load();
        return parent::setNomPere($nomPere);
    }

    public function getNomPere()
    {
        $this->__load();
        return parent::getNomPere();
    }

    public function setNomMere($nomMere)
    {
        $this->__load();
        return parent::setNomMere($nomMere);
    }

    public function getNomMere()
    {
        $this->__load();
        return parent::getNomMere();
    }

    public function setAdressePere($adressePere)
    {
        $this->__load();
        return parent::setAdressePere($adressePere);
    }

    public function getAdressePere()
    {
        $this->__load();
        return parent::getAdressePere();
    }

    public function setAdresseMere($adresseMere)
    {
        $this->__load();
        return parent::setAdresseMere($adresseMere);
    }

    public function getAdresseMere()
    {
        $this->__load();
        return parent::getAdresseMere();
    }

    public function setPersonneAcontacter($personneAcontacter)
    {
        $this->__load();
        return parent::setPersonneAcontacter($personneAcontacter);
    }

    public function getPersonneAcontacter()
    {
        $this->__load();
        return parent::getPersonneAcontacter();
    }

    public function setDernierEtablissementFreq($dernierEtablissementFreq)
    {
        $this->__load();
        return parent::setDernierEtablissementFreq($dernierEtablissementFreq);
    }

    public function getDernierEtablissementFreq()
    {
        $this->__load();
        return parent::getDernierEtablissementFreq();
    }

    public function setSexe(\School\StudentBundle\Entity\Sexe $sexe = NULL)
    {
        $this->__load();
        return parent::setSexe($sexe);
    }

    public function getSexe()
    {
        $this->__load();
        return parent::getSexe();
    }

    public function setPhoto(\School\StudentBundle\Entity\Image $photo = NULL)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function setClasse(\School\StudentBundle\Entity\Classe $classe = NULL)
    {
        $this->__load();
        return parent::setClasse($classe);
    }

    public function getClasse()
    {
        $this->__load();
        return parent::getClasse();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'matricule', 'nom', 'dateNaissance', 'lieuNaissance', 'nomPere', 'nomMere', 'adressePere', 'adresseMere', 'personneAcontacter', 'dernierEtablissementFreq', 'sexe', 'photo', 'classe');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}