<?php

namespace Proxies\__CG__\School\StudentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \School\StudentBundle\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'matricule', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nom', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'sexe', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'dateNaissance', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'lieuNaissance', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nomPere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nomMere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'adressePere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'adresseMere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'personneAcontacter', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'dernierEtablissementFreq', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'photo', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'classe');
        }

        return array('__isInitialized__', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'matricule', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nom', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'sexe', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'dateNaissance', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'lieuNaissance', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nomPere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'nomMere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'adressePere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'adresseMere', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'personneAcontacter', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'dernierEtablissementFreq', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'photo', '' . "\0" . 'School\\StudentBundle\\Entity\\Student' . "\0" . 'classe');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Student $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', array($matricule));

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', array());

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', array($dateNaissance));

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', array());

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance($lieuNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', array($lieuNaissance));

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', array());

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPere($nomPere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPere', array($nomPere));

        return parent::setNomPere($nomPere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPere', array());

        return parent::getNomPere();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMere($nomMere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMere', array($nomMere));

        return parent::setNomMere($nomMere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMere', array());

        return parent::getNomMere();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePere($adressePere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePere', array($adressePere));

        return parent::setAdressePere($adressePere);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePere', array());

        return parent::getAdressePere();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseMere($adresseMere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseMere', array($adresseMere));

        return parent::setAdresseMere($adresseMere);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseMere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseMere', array());

        return parent::getAdresseMere();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonneAcontacter($personneAcontacter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonneAcontacter', array($personneAcontacter));

        return parent::setPersonneAcontacter($personneAcontacter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonneAcontacter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonneAcontacter', array());

        return parent::getPersonneAcontacter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDernierEtablissementFreq($dernierEtablissementFreq)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDernierEtablissementFreq', array($dernierEtablissementFreq));

        return parent::setDernierEtablissementFreq($dernierEtablissementFreq);
    }

    /**
     * {@inheritDoc}
     */
    public function getDernierEtablissementFreq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDernierEtablissementFreq', array());

        return parent::getDernierEtablissementFreq();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(\School\StudentBundle\Entity\Sexe $sexe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(\School\StudentBundle\Entity\Image $photo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(\School\StudentBundle\Entity\Classe $classe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

}
