SchoolMatiereBundle_categorie:
    resource: "@SchoolMatiereBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
    
SchoolMatiereBundle_matiere:
    resource: "@SchoolMatiereBundle/Resources/config/routing/matiere.yml"
    prefix:   /matiere
        
SchoolMatiereBundle_estdispense:
    resource: "@SchoolMatiereBundle/Resources/config/routing/estdispense.yml"
    prefix:   /estdispense