parameters:
#    school_matiere.example.class: School\MatiereBundle\Example

services:
#    school_matiere.example:
#        class: %school_matiere.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
