absence:
    path:     /
    defaults: { _controller: "SchoolStudentBundle:Absence:index" }

absence_show:
    path:     /{id}/show
    defaults: { _controller: "SchoolStudentBundle:Absence:show" }

absence_new:
    path:     /new
    defaults: { _controller: "SchoolStudentBundle:Absence:new" }

absence_create:
    path:     /create
    defaults: { _controller: "SchoolStudentBundle:Absence:create" }
    requirements: { _method: post }

absence_edit:
    path:     /{id}/edit
    defaults: { _controller: "SchoolStudentBundle:Absence:edit" }

absence_update:
    path:     /{id}/update
    defaults: { _controller: "SchoolStudentBundle:Absence:update" }
    requirements: { _method: post|put }

absence_delete:
    path:     /{id}/delete
    defaults: { _controller: "SchoolStudentBundle:Absence:delete" }
    requirements: { _method: post|delete }
    
absence_classe:
    path:     /Classe-{idClasse}/Sequence-{idSeq}
    defaults: { _controller: "SchoolStudentBundle:Absence:absenceClasse" }
    requirements: 
        idClasse: \d+
        idSeq: \d+
