school_student_homepage:
    path:     /hello/{name}
    defaults: { _controller: SchoolStudentBundle:Default:index }

school_student_show:
    path:       /student/{id}
    defaults: { _controller: SchoolStudentBundle:Student:show}
    requirements:
      id: \d+

school_student_add:
    path:       /student/add
    defaults: { _controller: SchoolStudentBundle:Student:add}

school_student_list:
    path:       /listeEleves
    defaults: { _controller: SchoolStudentBundle:Student:list}

school_student_edit:
    path:       /student/edit/{id}
    defaults: { _controller: SchoolStudentBundle:Student:edit}
    requirements:
      id: \d+

school_student_delete:
    path:       /student/{id}/delete
    defaults: { _controller: SchoolStudentBundle:Student:delete}
    requirements:
      id: \d+