SchoolStudentBundle_classe:
    resource: "@SchoolStudentBundle/Resources/config/routing/classe.yml"
    prefix:   /classe

SchoolStudentBundle_inscription:
    resource: "@SchoolStudentBundle/Resources/config/routing/inscription.yml"
    prefix:   /inscription


SchoolStudentBundle_student:
    resource: "@SchoolStudentBundle/Resources/config/routing/student.yml"
    prefix:   /student

SchoolStudentBundle_cycle:
    resource: "@SchoolStudentBundle/Resources/config/routing/cycle.yml"
    prefix:   /cycle
    
    
SchoolStudentBundle_absence:
    resource: "@SchoolStudentBundle/Resources/config/routing/absence.yml"
    prefix:   /absence
