school_student_homepage:
    path:     /hello/{name}
    defaults: { _controller: SchoolStudentBundle:Default:index }

school_student_show:
    path:       /Gestion/student/{id}
    defaults: { _controller: SchoolStudentBundle:Student:show}
    requirements:
      id: \d+

school_student_add:
    path:       /Gestion/student/add
    defaults: { _controller: SchoolStudentBundle:Student:add}

school_student_list:
    path:       /Gestion/listeEleves
    defaults: { _controller: SchoolStudentBundle:Student:list}

school_student_edit:
    path:       /Gestion/student/edit/{id}
    defaults: { _controller: SchoolStudentBundle:Student:edit}
    requirements:
      id: \d+

school_student_delete:
    path:       /Gestion/student/{id}/delete
    defaults: { _controller: SchoolStudentBundle:Student:delete}
    requirements:
      id: \d+
      
      
SchoolStudentBundle_classe:
    resource: "@SchoolStudentBundle/Resources/config/routing/classe.yml"
    prefix:   /classe
