parameters:
#    school_student.example.class: School\StudentBundle\Example

services:
#    school_student.example:
#        class: %school_student.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
