school_note_homepage:
    path:     /hello/{name}
    defaults: { _controller: SchoolNoteBundle:Default:index }

SchoolNoteBundle_sequence:
    resource: "@SchoolNoteBundle/Resources/config/routing/sequence.yml"
    prefix:   /sequence

SchoolNoteBundle_evaluation:
    resource: "@SchoolNoteBundle/Resources/config/routing/evaluation.yml"
    prefix:   /evaluation
    
SchoolNoteBundle_bulletin:
    resource: "@SchoolNoteBundle/Resources/config/routing/bulletin.yml"
    prefix:   /bulletin