parameters:
#    school_note.example.class: School\NoteBundle\Example

services:
#    school_note.example:
#        class: %school_note.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
