parameters:
#    school_config.example.class: School\ConfigBundle\Example

services:
#    school_config.example:
#        class: %school_config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
